name: test-python-package

on: [push, pull_request]

jobs:
  build-and-test:
    outputs:
      VERSION: ${{ steps.get-version.outputs.VERSION }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1
      
    - uses: actions/setup-python@v5
      name: Install Python
      with:
          python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip --break-system-packages
        python -m pip install --user pytest hypothesis==6.72.4 wheel

    - name: Build wheel files
      run: |
        cd ${GITHUB_WORKSPACE}
        mkdir ${GITHUB_WORKSPACE}/wheel_files
        pip wheel . --wheel-dir ${GITHUB_WORKSPACE}/wheel_files

    - name: Upload wheel files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheel-files
        path: ./wheel_files/regbench_data*.whl